/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl2.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl2.myDsl.DictionaryEntry;
import org.xtext.example.mydsl2.myDsl.MakeStatement;
import org.xtext.example.mydsl2.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dictionary Entry</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.impl.DictionaryEntryImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.impl.DictionaryEntryImpl#getFieldType <em>Field Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.impl.DictionaryEntryImpl#isStatus <em>Status</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.impl.DictionaryEntryImpl#isUniqueKey <em>Unique Key</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.impl.DictionaryEntryImpl#getRefDictionary <em>Ref Dictionary</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DictionaryEntryImpl extends MinimalEObjectImpl.Container implements DictionaryEntry
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getFieldType() <em>Field Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFieldType()
   * @generated
   * @ordered
   */
  protected static final String FIELD_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFieldType() <em>Field Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFieldType()
   * @generated
   * @ordered
   */
  protected String fieldType = FIELD_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #isStatus() <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isStatus()
   * @generated
   * @ordered
   */
  protected static final boolean STATUS_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isStatus() <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isStatus()
   * @generated
   * @ordered
   */
  protected boolean status = STATUS_EDEFAULT;

  /**
   * The default value of the '{@link #isUniqueKey() <em>Unique Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUniqueKey()
   * @generated
   * @ordered
   */
  protected static final boolean UNIQUE_KEY_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isUniqueKey() <em>Unique Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUniqueKey()
   * @generated
   * @ordered
   */
  protected boolean uniqueKey = UNIQUE_KEY_EDEFAULT;

  /**
   * The cached value of the '{@link #getRefDictionary() <em>Ref Dictionary</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRefDictionary()
   * @generated
   * @ordered
   */
  protected MakeStatement refDictionary;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DictionaryEntryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.DICTIONARY_ENTRY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.DICTIONARY_ENTRY__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFieldType()
  {
    return fieldType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFieldType(String newFieldType)
  {
    String oldFieldType = fieldType;
    fieldType = newFieldType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.DICTIONARY_ENTRY__FIELD_TYPE, oldFieldType, fieldType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isStatus()
  {
    return status;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStatus(boolean newStatus)
  {
    boolean oldStatus = status;
    status = newStatus;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.DICTIONARY_ENTRY__STATUS, oldStatus, status));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isUniqueKey()
  {
    return uniqueKey;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUniqueKey(boolean newUniqueKey)
  {
    boolean oldUniqueKey = uniqueKey;
    uniqueKey = newUniqueKey;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.DICTIONARY_ENTRY__UNIQUE_KEY, oldUniqueKey, uniqueKey));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MakeStatement getRefDictionary()
  {
    if (refDictionary != null && refDictionary.eIsProxy())
    {
      InternalEObject oldRefDictionary = (InternalEObject)refDictionary;
      refDictionary = (MakeStatement)eResolveProxy(oldRefDictionary);
      if (refDictionary != oldRefDictionary)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.DICTIONARY_ENTRY__REF_DICTIONARY, oldRefDictionary, refDictionary));
      }
    }
    return refDictionary;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MakeStatement basicGetRefDictionary()
  {
    return refDictionary;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRefDictionary(MakeStatement newRefDictionary)
  {
    MakeStatement oldRefDictionary = refDictionary;
    refDictionary = newRefDictionary;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.DICTIONARY_ENTRY__REF_DICTIONARY, oldRefDictionary, refDictionary));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.DICTIONARY_ENTRY__NAME:
        return getName();
      case MyDslPackage.DICTIONARY_ENTRY__FIELD_TYPE:
        return getFieldType();
      case MyDslPackage.DICTIONARY_ENTRY__STATUS:
        return isStatus();
      case MyDslPackage.DICTIONARY_ENTRY__UNIQUE_KEY:
        return isUniqueKey();
      case MyDslPackage.DICTIONARY_ENTRY__REF_DICTIONARY:
        if (resolve) return getRefDictionary();
        return basicGetRefDictionary();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.DICTIONARY_ENTRY__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.DICTIONARY_ENTRY__FIELD_TYPE:
        setFieldType((String)newValue);
        return;
      case MyDslPackage.DICTIONARY_ENTRY__STATUS:
        setStatus((Boolean)newValue);
        return;
      case MyDslPackage.DICTIONARY_ENTRY__UNIQUE_KEY:
        setUniqueKey((Boolean)newValue);
        return;
      case MyDslPackage.DICTIONARY_ENTRY__REF_DICTIONARY:
        setRefDictionary((MakeStatement)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.DICTIONARY_ENTRY__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.DICTIONARY_ENTRY__FIELD_TYPE:
        setFieldType(FIELD_TYPE_EDEFAULT);
        return;
      case MyDslPackage.DICTIONARY_ENTRY__STATUS:
        setStatus(STATUS_EDEFAULT);
        return;
      case MyDslPackage.DICTIONARY_ENTRY__UNIQUE_KEY:
        setUniqueKey(UNIQUE_KEY_EDEFAULT);
        return;
      case MyDslPackage.DICTIONARY_ENTRY__REF_DICTIONARY:
        setRefDictionary((MakeStatement)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.DICTIONARY_ENTRY__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.DICTIONARY_ENTRY__FIELD_TYPE:
        return FIELD_TYPE_EDEFAULT == null ? fieldType != null : !FIELD_TYPE_EDEFAULT.equals(fieldType);
      case MyDslPackage.DICTIONARY_ENTRY__STATUS:
        return status != STATUS_EDEFAULT;
      case MyDslPackage.DICTIONARY_ENTRY__UNIQUE_KEY:
        return uniqueKey != UNIQUE_KEY_EDEFAULT;
      case MyDslPackage.DICTIONARY_ENTRY__REF_DICTIONARY:
        return refDictionary != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", fieldType: ");
    result.append(fieldType);
    result.append(", status: ");
    result.append(status);
    result.append(", uniqueKey: ");
    result.append(uniqueKey);
    result.append(')');
    return result.toString();
  }

} //DictionaryEntryImpl
