/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.CollectionFieldDefination;
import org.xtext.example.mydsl.myDsl.CollectionSchema;
import org.xtext.example.mydsl.myDsl.FieldType;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Collection Field Defination</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.CollectionFieldDefinationImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.CollectionFieldDefinationImpl#getFieldType <em>Field Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.CollectionFieldDefinationImpl#isStatus <em>Status</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.CollectionFieldDefinationImpl#isUniqueKey <em>Unique Key</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.CollectionFieldDefinationImpl#getRefCollection <em>Ref Collection</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CollectionFieldDefinationImpl extends MinimalEObjectImpl.Container implements CollectionFieldDefination
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getFieldType() <em>Field Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFieldType()
   * @generated
   * @ordered
   */
  protected static final FieldType FIELD_TYPE_EDEFAULT = FieldType.STRING;

  /**
   * The cached value of the '{@link #getFieldType() <em>Field Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFieldType()
   * @generated
   * @ordered
   */
  protected FieldType fieldType = FIELD_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #isStatus() <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isStatus()
   * @generated
   * @ordered
   */
  protected static final boolean STATUS_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isStatus() <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isStatus()
   * @generated
   * @ordered
   */
  protected boolean status = STATUS_EDEFAULT;

  /**
   * The default value of the '{@link #isUniqueKey() <em>Unique Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUniqueKey()
   * @generated
   * @ordered
   */
  protected static final boolean UNIQUE_KEY_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isUniqueKey() <em>Unique Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUniqueKey()
   * @generated
   * @ordered
   */
  protected boolean uniqueKey = UNIQUE_KEY_EDEFAULT;

  /**
   * The cached value of the '{@link #getRefCollection() <em>Ref Collection</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRefCollection()
   * @generated
   * @ordered
   */
  protected CollectionSchema refCollection;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CollectionFieldDefinationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.COLLECTION_FIELD_DEFINATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COLLECTION_FIELD_DEFINATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FieldType getFieldType()
  {
    return fieldType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFieldType(FieldType newFieldType)
  {
    FieldType oldFieldType = fieldType;
    fieldType = newFieldType == null ? FIELD_TYPE_EDEFAULT : newFieldType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COLLECTION_FIELD_DEFINATION__FIELD_TYPE, oldFieldType, fieldType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isStatus()
  {
    return status;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStatus(boolean newStatus)
  {
    boolean oldStatus = status;
    status = newStatus;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COLLECTION_FIELD_DEFINATION__STATUS, oldStatus, status));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isUniqueKey()
  {
    return uniqueKey;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUniqueKey(boolean newUniqueKey)
  {
    boolean oldUniqueKey = uniqueKey;
    uniqueKey = newUniqueKey;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COLLECTION_FIELD_DEFINATION__UNIQUE_KEY, oldUniqueKey, uniqueKey));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CollectionSchema getRefCollection()
  {
    if (refCollection != null && refCollection.eIsProxy())
    {
      InternalEObject oldRefCollection = (InternalEObject)refCollection;
      refCollection = (CollectionSchema)eResolveProxy(oldRefCollection);
      if (refCollection != oldRefCollection)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.COLLECTION_FIELD_DEFINATION__REF_COLLECTION, oldRefCollection, refCollection));
      }
    }
    return refCollection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CollectionSchema basicGetRefCollection()
  {
    return refCollection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRefCollection(CollectionSchema newRefCollection)
  {
    CollectionSchema oldRefCollection = refCollection;
    refCollection = newRefCollection;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COLLECTION_FIELD_DEFINATION__REF_COLLECTION, oldRefCollection, refCollection));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__NAME:
        return getName();
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__FIELD_TYPE:
        return getFieldType();
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__STATUS:
        return isStatus();
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__UNIQUE_KEY:
        return isUniqueKey();
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__REF_COLLECTION:
        if (resolve) return getRefCollection();
        return basicGetRefCollection();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__FIELD_TYPE:
        setFieldType((FieldType)newValue);
        return;
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__STATUS:
        setStatus((Boolean)newValue);
        return;
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__UNIQUE_KEY:
        setUniqueKey((Boolean)newValue);
        return;
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__REF_COLLECTION:
        setRefCollection((CollectionSchema)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__FIELD_TYPE:
        setFieldType(FIELD_TYPE_EDEFAULT);
        return;
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__STATUS:
        setStatus(STATUS_EDEFAULT);
        return;
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__UNIQUE_KEY:
        setUniqueKey(UNIQUE_KEY_EDEFAULT);
        return;
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__REF_COLLECTION:
        setRefCollection((CollectionSchema)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__FIELD_TYPE:
        return fieldType != FIELD_TYPE_EDEFAULT;
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__STATUS:
        return status != STATUS_EDEFAULT;
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__UNIQUE_KEY:
        return uniqueKey != UNIQUE_KEY_EDEFAULT;
      case MyDslPackage.COLLECTION_FIELD_DEFINATION__REF_COLLECTION:
        return refCollection != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", fieldType: ");
    result.append(fieldType);
    result.append(", status: ");
    result.append(status);
    result.append(", uniqueKey: ");
    result.append(uniqueKey);
    result.append(')');
    return result.toString();
  }

} //CollectionFieldDefinationImpl
