/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl2.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dictionary Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.DictionaryEntry#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.DictionaryEntry#getFieldType <em>Field Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.DictionaryEntry#isStatus <em>Status</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.DictionaryEntry#isUniqueKey <em>Unique Key</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.DictionaryEntry#getRefDictionary <em>Ref Dictionary</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getDictionaryEntry()
 * @model
 * @generated
 */
public interface DictionaryEntry extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getDictionaryEntry_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.myDsl.DictionaryEntry#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Field Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field Type</em>' attribute.
   * @see #setFieldType(String)
   * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getDictionaryEntry_FieldType()
   * @model
   * @generated
   */
  String getFieldType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.myDsl.DictionaryEntry#getFieldType <em>Field Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field Type</em>' attribute.
   * @see #getFieldType()
   * @generated
   */
  void setFieldType(String value);

  /**
   * Returns the value of the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Status</em>' attribute.
   * @see #setStatus(boolean)
   * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getDictionaryEntry_Status()
   * @model
   * @generated
   */
  boolean isStatus();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.myDsl.DictionaryEntry#isStatus <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Status</em>' attribute.
   * @see #isStatus()
   * @generated
   */
  void setStatus(boolean value);

  /**
   * Returns the value of the '<em><b>Unique Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unique Key</em>' attribute.
   * @see #setUniqueKey(boolean)
   * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getDictionaryEntry_UniqueKey()
   * @model
   * @generated
   */
  boolean isUniqueKey();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.myDsl.DictionaryEntry#isUniqueKey <em>Unique Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unique Key</em>' attribute.
   * @see #isUniqueKey()
   * @generated
   */
  void setUniqueKey(boolean value);

  /**
   * Returns the value of the '<em><b>Ref Dictionary</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref Dictionary</em>' reference.
   * @see #setRefDictionary(MakeStatement)
   * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getDictionaryEntry_RefDictionary()
   * @model
   * @generated
   */
  MakeStatement getRefDictionary();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.myDsl.DictionaryEntry#getRefDictionary <em>Ref Dictionary</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref Dictionary</em>' reference.
   * @see #getRefDictionary()
   * @generated
   */
  void setRefDictionary(MakeStatement value);

} // DictionaryEntry
