/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl2.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.Model#getConnection <em>Connection</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.Model#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Connection</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connection</em>' containment reference.
   * @see #setConnection(ConnectionStatement)
   * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getModel_Connection()
   * @model containment="true"
   * @generated
   */
  ConnectionStatement getConnection();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.myDsl.Model#getConnection <em>Connection</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Connection</em>' containment reference.
   * @see #getConnection()
   * @generated
   */
  void setConnection(ConnectionStatement value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl2.myDsl.OperationStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getModel_Statements()
   * @model containment="true"
   * @generated
   */
  EList<OperationStatement> getStatements();

} // Model
