/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl2.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Other Operation Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.OtherOperationStatement#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.OtherOperationStatement#getCollection <em>Collection</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.OtherOperationStatement#getEntries <em>Entries</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getOtherOperationStatement()
 * @model
 * @generated
 */
public interface OtherOperationStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getOtherOperationStatement_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.myDsl.OtherOperationStatement#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Collection</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Collection</em>' reference.
   * @see #setCollection(MakeStatement)
   * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getOtherOperationStatement_Collection()
   * @model
   * @generated
   */
  MakeStatement getCollection();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.myDsl.OtherOperationStatement#getCollection <em>Collection</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Collection</em>' reference.
   * @see #getCollection()
   * @generated
   */
  void setCollection(MakeStatement value);

  /**
   * Returns the value of the '<em><b>Entries</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl2.myDsl.TaskDictionaryEntry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entries</em>' containment reference list.
   * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getOtherOperationStatement_Entries()
   * @model containment="true"
   * @generated
   */
  EList<TaskDictionaryEntry> getEntries();

} // OtherOperationStatement
