/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl1.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CRUD Operation And Collection Schema</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.CRUDOperationAndCollectionSchema#getSchema <em>Schema</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.myDsl.CRUDOperationAndCollectionSchema#getOperations <em>Operations</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getCRUDOperationAndCollectionSchema()
 * @model
 * @generated
 */
public interface CRUDOperationAndCollectionSchema extends EObject
{
  /**
   * Returns the value of the '<em><b>Schema</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schema</em>' containment reference.
   * @see #setSchema(CollectionSchema)
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getCRUDOperationAndCollectionSchema_Schema()
   * @model containment="true"
   * @generated
   */
  CollectionSchema getSchema();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myDsl.CRUDOperationAndCollectionSchema#getSchema <em>Schema</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Schema</em>' containment reference.
   * @see #getSchema()
   * @generated
   */
  void setSchema(CollectionSchema value);

  /**
   * Returns the value of the '<em><b>Operations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl1.myDsl.CRUDOperations}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operations</em>' containment reference list.
   * @see org.xtext.example.mydsl1.myDsl.MyDslPackage#getCRUDOperationAndCollectionSchema_Operations()
   * @model containment="true"
   * @generated
   */
  EList<CRUDOperations> getOperations();

} // CRUDOperationAndCollectionSchema
