/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl1.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl1.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl1/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.MongoDBImpl <em>Mongo DB</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.MongoDBImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getMongoDB()
   * @generated
   */
  int MONGO_DB = 0;

  /**
   * The feature id for the '<em><b>Models</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONGO_DB__MODELS = 0;

  /**
   * The number of structural features of the '<em>Mongo DB</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONGO_DB_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 1;

  /**
   * The feature id for the '<em><b>Connection</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONNECTION = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.CRUDOperationAndCollectionSchemaImpl <em>CRUD Operation And Collection Schema</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.CRUDOperationAndCollectionSchemaImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getCRUDOperationAndCollectionSchema()
   * @generated
   */
  int CRUD_OPERATION_AND_COLLECTION_SCHEMA = 2;

  /**
   * The feature id for the '<em><b>Schema</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRUD_OPERATION_AND_COLLECTION_SCHEMA__SCHEMA = 0;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRUD_OPERATION_AND_COLLECTION_SCHEMA__OPERATIONS = 1;

  /**
   * The number of structural features of the '<em>CRUD Operation And Collection Schema</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRUD_OPERATION_AND_COLLECTION_SCHEMA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.ConnectionStatementImpl <em>Connection Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.ConnectionStatementImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getConnectionStatement()
   * @generated
   */
  int CONNECTION_STATEMENT = 3;

  /**
   * The feature id for the '<em><b>Connection String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_STATEMENT__CONNECTION_STRING = 0;

  /**
   * The feature id for the '<em><b>Database Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_STATEMENT__DATABASE_NAME = 1;

  /**
   * The number of structural features of the '<em>Connection Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.CollectionSchemaImpl <em>Collection Schema</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.CollectionSchemaImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getCollectionSchema()
   * @generated
   */
  int COLLECTION_SCHEMA = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_SCHEMA__NAME = 0;

  /**
   * The feature id for the '<em><b>Defination</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_SCHEMA__DEFINATION = 1;

  /**
   * The number of structural features of the '<em>Collection Schema</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_SCHEMA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.CollectionFieldDefinationImpl <em>Collection Field Defination</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.CollectionFieldDefinationImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getCollectionFieldDefination()
   * @generated
   */
  int COLLECTION_FIELD_DEFINATION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_FIELD_DEFINATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Field Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_FIELD_DEFINATION__FIELD_TYPE = 1;

  /**
   * The feature id for the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_FIELD_DEFINATION__STATUS = 2;

  /**
   * The feature id for the '<em><b>Unique Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_FIELD_DEFINATION__UNIQUE_KEY = 3;

  /**
   * The feature id for the '<em><b>Ref Collection</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_FIELD_DEFINATION__REF_COLLECTION = 4;

  /**
   * The number of structural features of the '<em>Collection Field Defination</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_FIELD_DEFINATION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.CRUDOperationsImpl <em>CRUD Operations</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.CRUDOperationsImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getCRUDOperations()
   * @generated
   */
  int CRUD_OPERATIONS = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRUD_OPERATIONS__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRUD_OPERATIONS__TYPE = 1;

  /**
   * The feature id for the '<em><b>Collection</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRUD_OPERATIONS__COLLECTION = 2;

  /**
   * The feature id for the '<em><b>Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRUD_OPERATIONS__ENTRIES = 3;

  /**
   * The number of structural features of the '<em>CRUD Operations</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRUD_OPERATIONS_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.UpdateCollectionEntryImpl <em>Update Collection Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.UpdateCollectionEntryImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getUpdateCollectionEntry()
   * @generated
   */
  int UPDATE_COLLECTION_ENTRY = 7;

  /**
   * The feature id for the '<em><b>Value Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE_COLLECTION_ENTRY__VALUE_NAME = 0;

  /**
   * The feature id for the '<em><b>Value String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE_COLLECTION_ENTRY__VALUE_STRING = 1;

  /**
   * The feature id for the '<em><b>Value Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE_COLLECTION_ENTRY__VALUE_INT = 2;

  /**
   * The number of structural features of the '<em>Update Collection Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE_COLLECTION_ENTRY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.CollectionEntryImpl <em>Collection Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.CollectionEntryImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getCollectionEntry()
   * @generated
   */
  int COLLECTION_ENTRY = 8;

  /**
   * The feature id for the '<em><b>Value Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_ENTRY__VALUE_NAME = 0;

  /**
   * The feature id for the '<em><b>Value String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_ENTRY__VALUE_STRING = 1;

  /**
   * The feature id for the '<em><b>Value Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_ENTRY__VALUE_INT = 2;

  /**
   * The number of structural features of the '<em>Collection Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_ENTRY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.FieldType <em>Field Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.FieldType
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getFieldType()
   * @generated
   */
  int FIELD_TYPE = 9;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.MongoDB <em>Mongo DB</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mongo DB</em>'.
   * @see org.xtext.example.mydsl1.myDsl.MongoDB
   * @generated
   */
  EClass getMongoDB();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl1.myDsl.MongoDB#getModels <em>Models</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Models</em>'.
   * @see org.xtext.example.mydsl1.myDsl.MongoDB#getModels()
   * @see #getMongoDB()
   * @generated
   */
  EReference getMongoDB_Models();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl1.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl1.myDsl.Model#getConnection <em>Connection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Connection</em>'.
   * @see org.xtext.example.mydsl1.myDsl.Model#getConnection()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Connection();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl1.myDsl.Model#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.xtext.example.mydsl1.myDsl.Model#getStatements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Statements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.CRUDOperationAndCollectionSchema <em>CRUD Operation And Collection Schema</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CRUD Operation And Collection Schema</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CRUDOperationAndCollectionSchema
   * @generated
   */
  EClass getCRUDOperationAndCollectionSchema();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl1.myDsl.CRUDOperationAndCollectionSchema#getSchema <em>Schema</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Schema</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CRUDOperationAndCollectionSchema#getSchema()
   * @see #getCRUDOperationAndCollectionSchema()
   * @generated
   */
  EReference getCRUDOperationAndCollectionSchema_Schema();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl1.myDsl.CRUDOperationAndCollectionSchema#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CRUDOperationAndCollectionSchema#getOperations()
   * @see #getCRUDOperationAndCollectionSchema()
   * @generated
   */
  EReference getCRUDOperationAndCollectionSchema_Operations();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.ConnectionStatement <em>Connection Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connection Statement</em>'.
   * @see org.xtext.example.mydsl1.myDsl.ConnectionStatement
   * @generated
   */
  EClass getConnectionStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.ConnectionStatement#getConnectionString <em>Connection String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Connection String</em>'.
   * @see org.xtext.example.mydsl1.myDsl.ConnectionStatement#getConnectionString()
   * @see #getConnectionStatement()
   * @generated
   */
  EAttribute getConnectionStatement_ConnectionString();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.ConnectionStatement#getDatabaseName <em>Database Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Database Name</em>'.
   * @see org.xtext.example.mydsl1.myDsl.ConnectionStatement#getDatabaseName()
   * @see #getConnectionStatement()
   * @generated
   */
  EAttribute getConnectionStatement_DatabaseName();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.CollectionSchema <em>Collection Schema</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Collection Schema</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CollectionSchema
   * @generated
   */
  EClass getCollectionSchema();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.CollectionSchema#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CollectionSchema#getName()
   * @see #getCollectionSchema()
   * @generated
   */
  EAttribute getCollectionSchema_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl1.myDsl.CollectionSchema#getDefination <em>Defination</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Defination</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CollectionSchema#getDefination()
   * @see #getCollectionSchema()
   * @generated
   */
  EReference getCollectionSchema_Defination();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.CollectionFieldDefination <em>Collection Field Defination</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Collection Field Defination</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CollectionFieldDefination
   * @generated
   */
  EClass getCollectionFieldDefination();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.CollectionFieldDefination#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CollectionFieldDefination#getName()
   * @see #getCollectionFieldDefination()
   * @generated
   */
  EAttribute getCollectionFieldDefination_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.CollectionFieldDefination#getFieldType <em>Field Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Field Type</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CollectionFieldDefination#getFieldType()
   * @see #getCollectionFieldDefination()
   * @generated
   */
  EAttribute getCollectionFieldDefination_FieldType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.CollectionFieldDefination#isStatus <em>Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Status</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CollectionFieldDefination#isStatus()
   * @see #getCollectionFieldDefination()
   * @generated
   */
  EAttribute getCollectionFieldDefination_Status();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.CollectionFieldDefination#isUniqueKey <em>Unique Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unique Key</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CollectionFieldDefination#isUniqueKey()
   * @see #getCollectionFieldDefination()
   * @generated
   */
  EAttribute getCollectionFieldDefination_UniqueKey();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl1.myDsl.CollectionFieldDefination#getRefCollection <em>Ref Collection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref Collection</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CollectionFieldDefination#getRefCollection()
   * @see #getCollectionFieldDefination()
   * @generated
   */
  EReference getCollectionFieldDefination_RefCollection();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.CRUDOperations <em>CRUD Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CRUD Operations</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CRUDOperations
   * @generated
   */
  EClass getCRUDOperations();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.CRUDOperations#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CRUDOperations#getName()
   * @see #getCRUDOperations()
   * @generated
   */
  EAttribute getCRUDOperations_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.CRUDOperations#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CRUDOperations#getType()
   * @see #getCRUDOperations()
   * @generated
   */
  EAttribute getCRUDOperations_Type();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl1.myDsl.CRUDOperations#getCollection <em>Collection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Collection</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CRUDOperations#getCollection()
   * @see #getCRUDOperations()
   * @generated
   */
  EReference getCRUDOperations_Collection();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl1.myDsl.CRUDOperations#getEntries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entries</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CRUDOperations#getEntries()
   * @see #getCRUDOperations()
   * @generated
   */
  EReference getCRUDOperations_Entries();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.UpdateCollectionEntry <em>Update Collection Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Update Collection Entry</em>'.
   * @see org.xtext.example.mydsl1.myDsl.UpdateCollectionEntry
   * @generated
   */
  EClass getUpdateCollectionEntry();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.UpdateCollectionEntry#getValueName <em>Value Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value Name</em>'.
   * @see org.xtext.example.mydsl1.myDsl.UpdateCollectionEntry#getValueName()
   * @see #getUpdateCollectionEntry()
   * @generated
   */
  EAttribute getUpdateCollectionEntry_ValueName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.UpdateCollectionEntry#getValueString <em>Value String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value String</em>'.
   * @see org.xtext.example.mydsl1.myDsl.UpdateCollectionEntry#getValueString()
   * @see #getUpdateCollectionEntry()
   * @generated
   */
  EAttribute getUpdateCollectionEntry_ValueString();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.UpdateCollectionEntry#getValueInt <em>Value Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value Int</em>'.
   * @see org.xtext.example.mydsl1.myDsl.UpdateCollectionEntry#getValueInt()
   * @see #getUpdateCollectionEntry()
   * @generated
   */
  EAttribute getUpdateCollectionEntry_ValueInt();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.CollectionEntry <em>Collection Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Collection Entry</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CollectionEntry
   * @generated
   */
  EClass getCollectionEntry();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.CollectionEntry#getValueName <em>Value Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value Name</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CollectionEntry#getValueName()
   * @see #getCollectionEntry()
   * @generated
   */
  EAttribute getCollectionEntry_ValueName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.CollectionEntry#getValueString <em>Value String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value String</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CollectionEntry#getValueString()
   * @see #getCollectionEntry()
   * @generated
   */
  EAttribute getCollectionEntry_ValueString();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.CollectionEntry#getValueInt <em>Value Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value Int</em>'.
   * @see org.xtext.example.mydsl1.myDsl.CollectionEntry#getValueInt()
   * @see #getCollectionEntry()
   * @generated
   */
  EAttribute getCollectionEntry_ValueInt();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl1.myDsl.FieldType <em>Field Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Field Type</em>'.
   * @see org.xtext.example.mydsl1.myDsl.FieldType
   * @generated
   */
  EEnum getFieldType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.MongoDBImpl <em>Mongo DB</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.MongoDBImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getMongoDB()
     * @generated
     */
    EClass MONGO_DB = eINSTANCE.getMongoDB();

    /**
     * The meta object literal for the '<em><b>Models</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MONGO_DB__MODELS = eINSTANCE.getMongoDB_Models();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Connection</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CONNECTION = eINSTANCE.getModel_Connection();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STATEMENTS = eINSTANCE.getModel_Statements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.CRUDOperationAndCollectionSchemaImpl <em>CRUD Operation And Collection Schema</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.CRUDOperationAndCollectionSchemaImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getCRUDOperationAndCollectionSchema()
     * @generated
     */
    EClass CRUD_OPERATION_AND_COLLECTION_SCHEMA = eINSTANCE.getCRUDOperationAndCollectionSchema();

    /**
     * The meta object literal for the '<em><b>Schema</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CRUD_OPERATION_AND_COLLECTION_SCHEMA__SCHEMA = eINSTANCE.getCRUDOperationAndCollectionSchema_Schema();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CRUD_OPERATION_AND_COLLECTION_SCHEMA__OPERATIONS = eINSTANCE.getCRUDOperationAndCollectionSchema_Operations();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.ConnectionStatementImpl <em>Connection Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.ConnectionStatementImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getConnectionStatement()
     * @generated
     */
    EClass CONNECTION_STATEMENT = eINSTANCE.getConnectionStatement();

    /**
     * The meta object literal for the '<em><b>Connection String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECTION_STATEMENT__CONNECTION_STRING = eINSTANCE.getConnectionStatement_ConnectionString();

    /**
     * The meta object literal for the '<em><b>Database Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECTION_STATEMENT__DATABASE_NAME = eINSTANCE.getConnectionStatement_DatabaseName();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.CollectionSchemaImpl <em>Collection Schema</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.CollectionSchemaImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getCollectionSchema()
     * @generated
     */
    EClass COLLECTION_SCHEMA = eINSTANCE.getCollectionSchema();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLLECTION_SCHEMA__NAME = eINSTANCE.getCollectionSchema_Name();

    /**
     * The meta object literal for the '<em><b>Defination</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLLECTION_SCHEMA__DEFINATION = eINSTANCE.getCollectionSchema_Defination();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.CollectionFieldDefinationImpl <em>Collection Field Defination</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.CollectionFieldDefinationImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getCollectionFieldDefination()
     * @generated
     */
    EClass COLLECTION_FIELD_DEFINATION = eINSTANCE.getCollectionFieldDefination();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLLECTION_FIELD_DEFINATION__NAME = eINSTANCE.getCollectionFieldDefination_Name();

    /**
     * The meta object literal for the '<em><b>Field Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLLECTION_FIELD_DEFINATION__FIELD_TYPE = eINSTANCE.getCollectionFieldDefination_FieldType();

    /**
     * The meta object literal for the '<em><b>Status</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLLECTION_FIELD_DEFINATION__STATUS = eINSTANCE.getCollectionFieldDefination_Status();

    /**
     * The meta object literal for the '<em><b>Unique Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLLECTION_FIELD_DEFINATION__UNIQUE_KEY = eINSTANCE.getCollectionFieldDefination_UniqueKey();

    /**
     * The meta object literal for the '<em><b>Ref Collection</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLLECTION_FIELD_DEFINATION__REF_COLLECTION = eINSTANCE.getCollectionFieldDefination_RefCollection();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.CRUDOperationsImpl <em>CRUD Operations</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.CRUDOperationsImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getCRUDOperations()
     * @generated
     */
    EClass CRUD_OPERATIONS = eINSTANCE.getCRUDOperations();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CRUD_OPERATIONS__NAME = eINSTANCE.getCRUDOperations_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CRUD_OPERATIONS__TYPE = eINSTANCE.getCRUDOperations_Type();

    /**
     * The meta object literal for the '<em><b>Collection</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CRUD_OPERATIONS__COLLECTION = eINSTANCE.getCRUDOperations_Collection();

    /**
     * The meta object literal for the '<em><b>Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CRUD_OPERATIONS__ENTRIES = eINSTANCE.getCRUDOperations_Entries();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.UpdateCollectionEntryImpl <em>Update Collection Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.UpdateCollectionEntryImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getUpdateCollectionEntry()
     * @generated
     */
    EClass UPDATE_COLLECTION_ENTRY = eINSTANCE.getUpdateCollectionEntry();

    /**
     * The meta object literal for the '<em><b>Value Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UPDATE_COLLECTION_ENTRY__VALUE_NAME = eINSTANCE.getUpdateCollectionEntry_ValueName();

    /**
     * The meta object literal for the '<em><b>Value String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UPDATE_COLLECTION_ENTRY__VALUE_STRING = eINSTANCE.getUpdateCollectionEntry_ValueString();

    /**
     * The meta object literal for the '<em><b>Value Int</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UPDATE_COLLECTION_ENTRY__VALUE_INT = eINSTANCE.getUpdateCollectionEntry_ValueInt();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.CollectionEntryImpl <em>Collection Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.CollectionEntryImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getCollectionEntry()
     * @generated
     */
    EClass COLLECTION_ENTRY = eINSTANCE.getCollectionEntry();

    /**
     * The meta object literal for the '<em><b>Value Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLLECTION_ENTRY__VALUE_NAME = eINSTANCE.getCollectionEntry_ValueName();

    /**
     * The meta object literal for the '<em><b>Value String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLLECTION_ENTRY__VALUE_STRING = eINSTANCE.getCollectionEntry_ValueString();

    /**
     * The meta object literal for the '<em><b>Value Int</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLLECTION_ENTRY__VALUE_INT = eINSTANCE.getCollectionEntry_ValueInt();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.FieldType <em>Field Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.FieldType
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getFieldType()
     * @generated
     */
    EEnum FIELD_TYPE = eINSTANCE.getFieldType();

  }

} //MyDslPackage
