/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CRUD Operations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.CRUDOperations#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.CRUDOperations#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.CRUDOperations#getCollection <em>Collection</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.CRUDOperations#getEntries <em>Entries</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.CRUDOperations#getUpdateOperation <em>Update Operation</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.CRUDOperations#getCriteria <em>Criteria</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCRUDOperations()
 * @model
 * @generated
 */
public interface CRUDOperations extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCRUDOperations_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.CRUDOperations#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.Operation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.Operation
   * @see #setType(Operation)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCRUDOperations_Type()
   * @model
   * @generated
   */
  Operation getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.CRUDOperations#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.Operation
   * @see #getType()
   * @generated
   */
  void setType(Operation value);

  /**
   * Returns the value of the '<em><b>Collection</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Collection</em>' reference.
   * @see #setCollection(CollectionSchema)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCRUDOperations_Collection()
   * @model
   * @generated
   */
  CollectionSchema getCollection();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.CRUDOperations#getCollection <em>Collection</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Collection</em>' reference.
   * @see #getCollection()
   * @generated
   */
  void setCollection(CollectionSchema value);

  /**
   * Returns the value of the '<em><b>Entries</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.CollectionEntry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entries</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCRUDOperations_Entries()
   * @model containment="true"
   * @generated
   */
  EList<CollectionEntry> getEntries();

  /**
   * Returns the value of the '<em><b>Update Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Update Operation</em>' attribute.
   * @see #setUpdateOperation(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCRUDOperations_UpdateOperation()
   * @model
   * @generated
   */
  String getUpdateOperation();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.CRUDOperations#getUpdateOperation <em>Update Operation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Update Operation</em>' attribute.
   * @see #getUpdateOperation()
   * @generated
   */
  void setUpdateOperation(String value);

  /**
   * Returns the value of the '<em><b>Criteria</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.CollectionEntry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Criteria</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCRUDOperations_Criteria()
   * @model containment="true"
   * @generated
   */
  EList<CollectionEntry> getCriteria();

} // CRUDOperations
