/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage
 * @generated
 */
public interface MyDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslFactory eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Mongo DB</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mongo DB</em>'.
   * @generated
   */
  MongoDB createMongoDB();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>CRUD Operation And Collection Schema</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CRUD Operation And Collection Schema</em>'.
   * @generated
   */
  CRUDOperationAndCollectionSchema createCRUDOperationAndCollectionSchema();

  /**
   * Returns a new object of class '<em>Connection Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Connection Statement</em>'.
   * @generated
   */
  ConnectionStatement createConnectionStatement();

  /**
   * Returns a new object of class '<em>Collection Schema</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Collection Schema</em>'.
   * @generated
   */
  CollectionSchema createCollectionSchema();

  /**
   * Returns a new object of class '<em>Collection Field Defination</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Collection Field Defination</em>'.
   * @generated
   */
  CollectionFieldDefination createCollectionFieldDefination();

  /**
   * Returns a new object of class '<em>CRUD Operations</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CRUD Operations</em>'.
   * @generated
   */
  CRUDOperations createCRUDOperations();

  /**
   * Returns a new object of class '<em>Collection Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Collection Entry</em>'.
   * @generated
   */
  CollectionEntry createCollectionEntry();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyDslPackage getMyDslPackage();

} //MyDslFactory
