/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl1.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl1.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl1/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.MongoDBImpl <em>Mongo DB</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.MongoDBImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getMongoDB()
   * @generated
   */
  int MONGO_DB = 0;

  /**
   * The feature id for the '<em><b>Models</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONGO_DB__MODELS = 0;

  /**
   * The number of structural features of the '<em>Mongo DB</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONGO_DB_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 1;

  /**
   * The feature id for the '<em><b>Connection</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONNECTION = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.OperationStatementImpl <em>Operation Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.OperationStatementImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getOperationStatement()
   * @generated
   */
  int OPERATION_STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Schema</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_STATEMENT__SCHEMA = 0;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_STATEMENT__OPERATIONS = 1;

  /**
   * The number of structural features of the '<em>Operation Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.ConnectionStatementImpl <em>Connection Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.ConnectionStatementImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getConnectionStatement()
   * @generated
   */
  int CONNECTION_STATEMENT = 3;

  /**
   * The feature id for the '<em><b>Connection String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_STATEMENT__CONNECTION_STRING = 0;

  /**
   * The feature id for the '<em><b>Database</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_STATEMENT__DATABASE = 1;

  /**
   * The number of structural features of the '<em>Connection Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.MakeStatementImpl <em>Make Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.MakeStatementImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getMakeStatement()
   * @generated
   */
  int MAKE_STATEMENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAKE_STATEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAKE_STATEMENT__ENTRIES = 1;

  /**
   * The number of structural features of the '<em>Make Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAKE_STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.DictionaryEntryImpl <em>Dictionary Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.DictionaryEntryImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getDictionaryEntry()
   * @generated
   */
  int DICTIONARY_ENTRY = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DICTIONARY_ENTRY__NAME = 0;

  /**
   * The feature id for the '<em><b>Field Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DICTIONARY_ENTRY__FIELD_TYPE = 1;

  /**
   * The feature id for the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DICTIONARY_ENTRY__STATUS = 2;

  /**
   * The feature id for the '<em><b>Unique Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DICTIONARY_ENTRY__UNIQUE_KEY = 3;

  /**
   * The feature id for the '<em><b>Ref Dictionary</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DICTIONARY_ENTRY__REF_DICTIONARY = 4;

  /**
   * The number of structural features of the '<em>Dictionary Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DICTIONARY_ENTRY_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.OtherOperationStatementImpl <em>Other Operation Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.OtherOperationStatementImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getOtherOperationStatement()
   * @generated
   */
  int OTHER_OPERATION_STATEMENT = 6;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OTHER_OPERATION_STATEMENT__TYPE = 0;

  /**
   * The feature id for the '<em><b>Collection</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OTHER_OPERATION_STATEMENT__COLLECTION = 1;

  /**
   * The feature id for the '<em><b>Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OTHER_OPERATION_STATEMENT__ENTRIES = 2;

  /**
   * The number of structural features of the '<em>Other Operation Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OTHER_OPERATION_STATEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myDsl.impl.TaskDictionaryEntryImpl <em>Task Dictionary Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myDsl.impl.TaskDictionaryEntryImpl
   * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getTaskDictionaryEntry()
   * @generated
   */
  int TASK_DICTIONARY_ENTRY = 7;

  /**
   * The feature id for the '<em><b>Value Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_DICTIONARY_ENTRY__VALUE_NAME = 0;

  /**
   * The feature id for the '<em><b>Value String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_DICTIONARY_ENTRY__VALUE_STRING = 1;

  /**
   * The feature id for the '<em><b>Value Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_DICTIONARY_ENTRY__VALUE_INT = 2;

  /**
   * The number of structural features of the '<em>Task Dictionary Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_DICTIONARY_ENTRY_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.MongoDB <em>Mongo DB</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mongo DB</em>'.
   * @see org.xtext.example.mydsl1.myDsl.MongoDB
   * @generated
   */
  EClass getMongoDB();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl1.myDsl.MongoDB#getModels <em>Models</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Models</em>'.
   * @see org.xtext.example.mydsl1.myDsl.MongoDB#getModels()
   * @see #getMongoDB()
   * @generated
   */
  EReference getMongoDB_Models();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl1.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl1.myDsl.Model#getConnection <em>Connection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Connection</em>'.
   * @see org.xtext.example.mydsl1.myDsl.Model#getConnection()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Connection();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl1.myDsl.Model#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.xtext.example.mydsl1.myDsl.Model#getStatements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Statements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.OperationStatement <em>Operation Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation Statement</em>'.
   * @see org.xtext.example.mydsl1.myDsl.OperationStatement
   * @generated
   */
  EClass getOperationStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl1.myDsl.OperationStatement#getSchema <em>Schema</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Schema</em>'.
   * @see org.xtext.example.mydsl1.myDsl.OperationStatement#getSchema()
   * @see #getOperationStatement()
   * @generated
   */
  EReference getOperationStatement_Schema();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl1.myDsl.OperationStatement#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.xtext.example.mydsl1.myDsl.OperationStatement#getOperations()
   * @see #getOperationStatement()
   * @generated
   */
  EReference getOperationStatement_Operations();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.ConnectionStatement <em>Connection Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connection Statement</em>'.
   * @see org.xtext.example.mydsl1.myDsl.ConnectionStatement
   * @generated
   */
  EClass getConnectionStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.ConnectionStatement#getConnectionString <em>Connection String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Connection String</em>'.
   * @see org.xtext.example.mydsl1.myDsl.ConnectionStatement#getConnectionString()
   * @see #getConnectionStatement()
   * @generated
   */
  EAttribute getConnectionStatement_ConnectionString();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.ConnectionStatement#getDatabase <em>Database</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Database</em>'.
   * @see org.xtext.example.mydsl1.myDsl.ConnectionStatement#getDatabase()
   * @see #getConnectionStatement()
   * @generated
   */
  EAttribute getConnectionStatement_Database();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.MakeStatement <em>Make Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Make Statement</em>'.
   * @see org.xtext.example.mydsl1.myDsl.MakeStatement
   * @generated
   */
  EClass getMakeStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.MakeStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl1.myDsl.MakeStatement#getName()
   * @see #getMakeStatement()
   * @generated
   */
  EAttribute getMakeStatement_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl1.myDsl.MakeStatement#getEntries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entries</em>'.
   * @see org.xtext.example.mydsl1.myDsl.MakeStatement#getEntries()
   * @see #getMakeStatement()
   * @generated
   */
  EReference getMakeStatement_Entries();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.DictionaryEntry <em>Dictionary Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dictionary Entry</em>'.
   * @see org.xtext.example.mydsl1.myDsl.DictionaryEntry
   * @generated
   */
  EClass getDictionaryEntry();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.DictionaryEntry#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl1.myDsl.DictionaryEntry#getName()
   * @see #getDictionaryEntry()
   * @generated
   */
  EAttribute getDictionaryEntry_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.DictionaryEntry#getFieldType <em>Field Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Field Type</em>'.
   * @see org.xtext.example.mydsl1.myDsl.DictionaryEntry#getFieldType()
   * @see #getDictionaryEntry()
   * @generated
   */
  EAttribute getDictionaryEntry_FieldType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.DictionaryEntry#isStatus <em>Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Status</em>'.
   * @see org.xtext.example.mydsl1.myDsl.DictionaryEntry#isStatus()
   * @see #getDictionaryEntry()
   * @generated
   */
  EAttribute getDictionaryEntry_Status();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.DictionaryEntry#isUniqueKey <em>Unique Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unique Key</em>'.
   * @see org.xtext.example.mydsl1.myDsl.DictionaryEntry#isUniqueKey()
   * @see #getDictionaryEntry()
   * @generated
   */
  EAttribute getDictionaryEntry_UniqueKey();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl1.myDsl.DictionaryEntry#getRefDictionary <em>Ref Dictionary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref Dictionary</em>'.
   * @see org.xtext.example.mydsl1.myDsl.DictionaryEntry#getRefDictionary()
   * @see #getDictionaryEntry()
   * @generated
   */
  EReference getDictionaryEntry_RefDictionary();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.OtherOperationStatement <em>Other Operation Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Other Operation Statement</em>'.
   * @see org.xtext.example.mydsl1.myDsl.OtherOperationStatement
   * @generated
   */
  EClass getOtherOperationStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.OtherOperationStatement#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl1.myDsl.OtherOperationStatement#getType()
   * @see #getOtherOperationStatement()
   * @generated
   */
  EAttribute getOtherOperationStatement_Type();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl1.myDsl.OtherOperationStatement#getCollection <em>Collection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Collection</em>'.
   * @see org.xtext.example.mydsl1.myDsl.OtherOperationStatement#getCollection()
   * @see #getOtherOperationStatement()
   * @generated
   */
  EReference getOtherOperationStatement_Collection();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl1.myDsl.OtherOperationStatement#getEntries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entries</em>'.
   * @see org.xtext.example.mydsl1.myDsl.OtherOperationStatement#getEntries()
   * @see #getOtherOperationStatement()
   * @generated
   */
  EReference getOtherOperationStatement_Entries();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myDsl.TaskDictionaryEntry <em>Task Dictionary Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task Dictionary Entry</em>'.
   * @see org.xtext.example.mydsl1.myDsl.TaskDictionaryEntry
   * @generated
   */
  EClass getTaskDictionaryEntry();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.TaskDictionaryEntry#getValueName <em>Value Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value Name</em>'.
   * @see org.xtext.example.mydsl1.myDsl.TaskDictionaryEntry#getValueName()
   * @see #getTaskDictionaryEntry()
   * @generated
   */
  EAttribute getTaskDictionaryEntry_ValueName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.TaskDictionaryEntry#getValueString <em>Value String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value String</em>'.
   * @see org.xtext.example.mydsl1.myDsl.TaskDictionaryEntry#getValueString()
   * @see #getTaskDictionaryEntry()
   * @generated
   */
  EAttribute getTaskDictionaryEntry_ValueString();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myDsl.TaskDictionaryEntry#getValueInt <em>Value Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value Int</em>'.
   * @see org.xtext.example.mydsl1.myDsl.TaskDictionaryEntry#getValueInt()
   * @see #getTaskDictionaryEntry()
   * @generated
   */
  EAttribute getTaskDictionaryEntry_ValueInt();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.MongoDBImpl <em>Mongo DB</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.MongoDBImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getMongoDB()
     * @generated
     */
    EClass MONGO_DB = eINSTANCE.getMongoDB();

    /**
     * The meta object literal for the '<em><b>Models</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MONGO_DB__MODELS = eINSTANCE.getMongoDB_Models();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Connection</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CONNECTION = eINSTANCE.getModel_Connection();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STATEMENTS = eINSTANCE.getModel_Statements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.OperationStatementImpl <em>Operation Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.OperationStatementImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getOperationStatement()
     * @generated
     */
    EClass OPERATION_STATEMENT = eINSTANCE.getOperationStatement();

    /**
     * The meta object literal for the '<em><b>Schema</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION_STATEMENT__SCHEMA = eINSTANCE.getOperationStatement_Schema();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION_STATEMENT__OPERATIONS = eINSTANCE.getOperationStatement_Operations();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.ConnectionStatementImpl <em>Connection Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.ConnectionStatementImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getConnectionStatement()
     * @generated
     */
    EClass CONNECTION_STATEMENT = eINSTANCE.getConnectionStatement();

    /**
     * The meta object literal for the '<em><b>Connection String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECTION_STATEMENT__CONNECTION_STRING = eINSTANCE.getConnectionStatement_ConnectionString();

    /**
     * The meta object literal for the '<em><b>Database</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECTION_STATEMENT__DATABASE = eINSTANCE.getConnectionStatement_Database();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.MakeStatementImpl <em>Make Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.MakeStatementImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getMakeStatement()
     * @generated
     */
    EClass MAKE_STATEMENT = eINSTANCE.getMakeStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAKE_STATEMENT__NAME = eINSTANCE.getMakeStatement_Name();

    /**
     * The meta object literal for the '<em><b>Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAKE_STATEMENT__ENTRIES = eINSTANCE.getMakeStatement_Entries();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.DictionaryEntryImpl <em>Dictionary Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.DictionaryEntryImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getDictionaryEntry()
     * @generated
     */
    EClass DICTIONARY_ENTRY = eINSTANCE.getDictionaryEntry();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DICTIONARY_ENTRY__NAME = eINSTANCE.getDictionaryEntry_Name();

    /**
     * The meta object literal for the '<em><b>Field Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DICTIONARY_ENTRY__FIELD_TYPE = eINSTANCE.getDictionaryEntry_FieldType();

    /**
     * The meta object literal for the '<em><b>Status</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DICTIONARY_ENTRY__STATUS = eINSTANCE.getDictionaryEntry_Status();

    /**
     * The meta object literal for the '<em><b>Unique Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DICTIONARY_ENTRY__UNIQUE_KEY = eINSTANCE.getDictionaryEntry_UniqueKey();

    /**
     * The meta object literal for the '<em><b>Ref Dictionary</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DICTIONARY_ENTRY__REF_DICTIONARY = eINSTANCE.getDictionaryEntry_RefDictionary();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.OtherOperationStatementImpl <em>Other Operation Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.OtherOperationStatementImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getOtherOperationStatement()
     * @generated
     */
    EClass OTHER_OPERATION_STATEMENT = eINSTANCE.getOtherOperationStatement();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OTHER_OPERATION_STATEMENT__TYPE = eINSTANCE.getOtherOperationStatement_Type();

    /**
     * The meta object literal for the '<em><b>Collection</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OTHER_OPERATION_STATEMENT__COLLECTION = eINSTANCE.getOtherOperationStatement_Collection();

    /**
     * The meta object literal for the '<em><b>Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OTHER_OPERATION_STATEMENT__ENTRIES = eINSTANCE.getOtherOperationStatement_Entries();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myDsl.impl.TaskDictionaryEntryImpl <em>Task Dictionary Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myDsl.impl.TaskDictionaryEntryImpl
     * @see org.xtext.example.mydsl1.myDsl.impl.MyDslPackageImpl#getTaskDictionaryEntry()
     * @generated
     */
    EClass TASK_DICTIONARY_ENTRY = eINSTANCE.getTaskDictionaryEntry();

    /**
     * The meta object literal for the '<em><b>Value Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_DICTIONARY_ENTRY__VALUE_NAME = eINSTANCE.getTaskDictionaryEntry_ValueName();

    /**
     * The meta object literal for the '<em><b>Value String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_DICTIONARY_ENTRY__VALUE_STRING = eINSTANCE.getTaskDictionaryEntry_ValueString();

    /**
     * The meta object literal for the '<em><b>Value Int</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_DICTIONARY_ENTRY__VALUE_INT = eINSTANCE.getTaskDictionaryEntry_ValueInt();

  }

} //MyDslPackage
