/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl1.validation;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.xtext.validation.Check;
import org.xtext.example.mydsl1.myDsl.CollectionFieldDefination;
import org.xtext.example.mydsl1.myDsl.CollectionSchema;
import org.xtext.example.mydsl1.myDsl.MyDslPackage;
import org.xtext.example.mydsl1.myDsl.CRUDOperationAndCollectionSchema;
import org.xtext.example.mydsl1.myDsl.CRUDOperations;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MyDslValidator extends AbstractMyDslValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	   @Check
	    public void checkNoSelfReference(CollectionSchema make) {
	        for (CollectionFieldDefination entry : make.getDefination()) {
	            if (entry.getRefCollection() != null && entry.getRefCollection().getName().equals(make.getName())) {
	                error("A collection cannot reference itself.", MyDslPackage.Literals.COLLECTION_SCHEMA__NAME);
	            }
	        }
	    }
	    @Check
	    public void validateCollectionName(CollectionSchema entry) {
	        // Check the dictionary name
	    	
	    	String name = entry.getName();
	        if (name != null && !name.isEmpty()) {
	            char firstChar = name.charAt(0);
	            if (!Character.isUpperCase(firstChar)) {
	                warning("collection name should start with an uppercase letter",
		                    MyDslPackage.Literals.COLLECTION_SCHEMA__NAME);
	            }
	        }
	    }
	    @Check
	    public void checkAttributeNameStartsWithLowercase(CollectionFieldDefination attr) {
	        if (!Character.isLowerCase(attr.getName().charAt(0))) {
	            warning("collection attribute name should start with a lowercase",
	            		MyDslPackage.Literals.COLLECTION_FIELD_DEFINATION__NAME);
	        }
	    }
	    @Check
	    public void checkUniqueTaskNames(CRUDOperationAndCollectionSchema statement) {
	        List<String> taskNames = new ArrayList<>();
	        for (CRUDOperations op : statement.getOperations()) {
	            String name = op.getName();
	            if (taskNames.contains(name)) {
	                warning("Duplicate task name '" + name + "'", null);
	            } else {
	                taskNames.add(name);
	            }
	        }
	    }
	    
}
