/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl1.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.mydsl1.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MyDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_OtherOperationStatement___CommaKeyword_1_1_9_0_UpdateKeyword_1_1_9_1_LeftCurlyBracketKeyword_1_1_9_2_RightCurlyBracketKeyword_1_1_9_4__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MyDslGrammarAccess) access;
		match_OtherOperationStatement___CommaKeyword_1_1_9_0_UpdateKeyword_1_1_9_1_LeftCurlyBracketKeyword_1_1_9_2_RightCurlyBracketKeyword_1_1_9_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getOtherOperationStatementAccess().getCommaKeyword_1_1_9_0()), new TokenAlias(false, false, grammarAccess.getOtherOperationStatementAccess().getUpdateKeyword_1_1_9_1()), new TokenAlias(false, false, grammarAccess.getOtherOperationStatementAccess().getLeftCurlyBracketKeyword_1_1_9_2()), new TokenAlias(false, false, grammarAccess.getOtherOperationStatementAccess().getRightCurlyBracketKeyword_1_1_9_4()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_OtherOperationStatement___CommaKeyword_1_1_9_0_UpdateKeyword_1_1_9_1_LeftCurlyBracketKeyword_1_1_9_2_RightCurlyBracketKeyword_1_1_9_4__q.equals(syntax))
				emit_OtherOperationStatement___CommaKeyword_1_1_9_0_UpdateKeyword_1_1_9_1_LeftCurlyBracketKeyword_1_1_9_2_RightCurlyBracketKeyword_1_1_9_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (',' 'update:' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     collection=[MakeStatement|ID] 'input:' '{' '}' (ambiguity) '}' (rule end)
	 *     entries+=TaskDictionaryEntry '}' (ambiguity) '}' (rule end)
	 
	 * </pre>
	 */
	protected void emit_OtherOperationStatement___CommaKeyword_1_1_9_0_UpdateKeyword_1_1_9_1_LeftCurlyBracketKeyword_1_1_9_2_RightCurlyBracketKeyword_1_1_9_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
